"""Load cleaned DVF sales into PostgreSQL.

A geo-dvf file covers one year, so loading replaces all the sales of that year in a single
transaction: re-running an ingestion is safe (idempotent), and readers never see a
half-loaded year. This does not rely on `id_mutation` being stable across publications.
"""

import logging
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import date
from decimal import Decimal

import pandas as pd
from sqlalchemy import Engine, delete, func, insert, text, update

from immo_paris.db.models import IngestionRun, Sale

logger = logging.getLogger(__name__)

# Columns written by COPY, in order; id and price_per_m2 are generated by PostgreSQL
COPY_COLUMNS = (
    "mutation_id",
    "ingestion_run_id",
    "sale_date",
    "commune_code",
    "postal_code",
    "address",
    "property_type",
    "surface_m2",
    "rooms",
    "price",
    "location",
)

CopyRow = tuple[object, ...]


@dataclass(frozen=True)
class DataSource:
    """Where a dataset comes from, recorded in ingestion_runs for lineage."""

    url: str
    sha256: str
    year: int


def none_if_missing(value: object) -> object:
    """Convert pandas missing values (NaN, NA) to None, which the driver writes as NULL."""
    return None if pd.isna(value) else value


def point_ewkt(longitude: float, latitude: float) -> str | None:
    """Return a WGS 84 point in the text format PostGIS accepts, or None if not geocoded."""
    if pd.isna(longitude) or pd.isna(latitude):
        return None
    # Longitude first: a point is (x, y)
    return f"SRID=4326;POINT({longitude} {latitude})"


def to_copy_rows(sales: pd.DataFrame, ingestion_run_id: int) -> Iterator[CopyRow]:
    """Convert cleaned sales into rows matching COPY_COLUMNS, with database-ready types."""
    for sale in sales.itertuples(index=False):
        yield (
            sale.mutation_id,
            ingestion_run_id,
            date.fromisoformat(sale.date),
            sale.commune_code,
            none_if_missing(sale.postal_code),
            sale.address,
            sale.property_type,
            int(sale.surface_m2),
            None if pd.isna(sale.rooms) else int(sale.rooms),
            # str() gives the shortest decimal form of the float, i.e. the published price
            Decimal(str(sale.price)),
            point_ewkt(sale.longitude, sale.latitude),
        )


def replace_year(
    engine: Engine, sales: pd.DataFrame, source: DataSource, row_counts: dict[str, int]
) -> int:
    """Atomically replace all the sales of `source.year` with `sales`.

    Returns the id of the ingestion run recorded for this load.
    """
    first_day, next_year_first_day = date(source.year, 1, 1), date(source.year + 1, 1, 1)
    sale_years = pd.to_datetime(sales["date"]).dt.year
    if not (sale_years == source.year).all():
        raise ValueError(f"All sales must be dated {source.year} to replace that year")

    with engine.begin() as conn:
        run_id = conn.execute(
            insert(IngestionRun)
            .values(
                source_url=source.url,
                source_sha256=source.sha256,
                data_year=source.year,
                row_counts=row_counts,
            )
            .returning(IngestionRun.id)
        ).scalar_one()

        deleted = conn.execute(
            delete(Sale).where(Sale.sale_date >= first_day, Sale.sale_date < next_year_first_day)
        ).rowcount

        # COPY streams all rows in a single command: much faster than one INSERT per row
        copy_sql = f"COPY sales ({', '.join(COPY_COLUMNS)}) FROM STDIN"
        with conn.connection.driver_connection.cursor() as cursor, cursor.copy(copy_sql) as copy:
            for row in to_copy_rows(sales, run_id):
                copy.write_row(row)

        # clock_timestamp(), not now(): now() is frozen at the start of the transaction
        conn.execute(
            update(IngestionRun)
            .where(IngestionRun.id == run_id)
            .values(finished_at=func.clock_timestamp())
        )

    logger.info(
        "Year %d replaced: %d sales deleted, %d loaded (ingestion run %d)",
        source.year,
        deleted,
        len(sales),
        run_id,
    )

    # After the commit, and CONCURRENTLY: the statistics stay readable while refreshing
    with engine.begin() as conn:
        conn.execute(text("REFRESH MATERIALIZED VIEW CONCURRENTLY commune_yearly_stats"))
    return run_id
