/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sales
         * @description Most recent sales first, one page at a time.
         */
        get: operations["list_sales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nearby Sales
         * @description Sales around a point, nearest first.
         */
        get: operations["list_nearby_sales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sale */
        get: operations["get_sale"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/communes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Commune Stats
         * @description Price per m² statistics by commune (arrondissement) for one year.
         */
        get: operations["list_commune_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommuneStats
         * @description Price per m² statistics of one commune for one year and property type.
         *
         *     Price statistics are null when `sales_count` is too low to be meaningful.
         */
        CommuneStats: {
            /** Commune Code */
            commune_code: string;
            /** Year */
            year: number;
            property_type: components["schemas"]["PropertyType"];
            /** Sales Count */
            sales_count: number;
            /** P25 Price Per M2 */
            p25_price_per_m2: number | null;
            /** Median Price Per M2 */
            median_price_per_m2: number | null;
            /** P75 Price Per M2 */
            p75_price_per_m2: number | null;
            /** Avg Surface M2 */
            avg_surface_m2: number | null;
            /** Commune Label */
            readonly commune_label: string;
        };
        /**
         * ErrorResponse
         * @description Body of 4xx/5xx errors raised by the API (except 422 validation errors).
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NearbySale */
        NearbySale: {
            /** Id */
            id: number;
            /** Mutation Id */
            mutation_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Commune Code */
            commune_code: string;
            /** Address */
            address: string;
            /** Postal Code */
            postal_code: string | null;
            property_type: components["schemas"]["PropertyType"];
            /** Surface M2 */
            surface_m2: number;
            /** Rooms */
            rooms: number | null;
            /** Price */
            price: number;
            /** Price Per M2 */
            price_per_m2: number;
            /** Longitude */
            longitude: number | null;
            /** Latitude */
            latitude: number | null;
            /** Distance M */
            distance_m: number;
            /** Commune Label */
            readonly commune_label: string;
        };
        /**
         * PropertyType
         * @enum {string}
         */
        PropertyType: "apartment" | "house";
        /**
         * Sale
         * @description Single-dwelling DVF sale, served to the web (Angular) and mobile (React Native) clients.
         */
        Sale: {
            /** Id */
            id: number;
            /** Mutation Id */
            mutation_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Commune Code */
            commune_code: string;
            /** Address */
            address: string;
            /** Postal Code */
            postal_code: string | null;
            property_type: components["schemas"]["PropertyType"];
            /** Surface M2 */
            surface_m2: number;
            /** Rooms */
            rooms: number | null;
            /** Price */
            price: number;
            /** Price Per M2 */
            price_per_m2: number;
            /** Longitude */
            longitude: number | null;
            /** Latitude */
            latitude: number | null;
            /** Commune Label */
            readonly commune_label: string;
        };
        /**
         * SalePage
         * @description One page of sales. Pass `next_cursor` back as `cursor` to get the next page.
         */
        SalePage: {
            /** Items */
            items: components["schemas"]["Sale"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sales: {
        parameters: {
            query?: {
                commune_code?: string | null;
                property_type?: components["schemas"]["PropertyType"] | null;
                limit?: number;
                /** @description next_cursor of the previous page */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nearby_sales: {
        parameters: {
            query: {
                /** @description Latitude (WGS 84) */
                lat: number;
                /** @description Longitude (WGS 84) */
                lng: number;
                /** @description Search radius in metres */
                radius_m?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbySale"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
            /** @description Sale not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commune_stats: {
        parameters: {
            query?: {
                /** @description Default: latest year */
                year?: number | null;
                property_type?: components["schemas"]["PropertyType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuneStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
